import { env } from "./config";

/** env[0] = Local | env[1] = Production */
export const baseURL = env[0];

export const endpoints = {
  authLogin: "Auth/adminLogin",
  authLogout: "Auth/logout",
  authRefreshToken: "Auth/refresh-token",
  admin: "Admin",
  role: "Role",
  customer: "Customer",
  promotion: "Promotion",
  review: "Review",
  scheduleBooking: "Order",
  country: "Country",
  city: "City",
  township: "Township",
  state: "State",
  merchant: "Merchant",
  driver: "Driver",
  vehicle: "Vehicle",
  vehicleType: "VehicleType",
  wallet: "Wallet",
  order: "Order",
  topupTransaction: "TopUpTransaction",
  withDrawTransaction: "WithDrawTransaction",
  reason: "Reason",
  paymentChannel: "PaymentChannel",
  sms: "Sms",
  simulation: "Simulation",
  sos: "Sos",
  travelRate: "TravelRate",
  kiloAmount: "KiloAmount",
  commissionConfig: "ConfigurationSetting",
  login: "auth/login",
  image: `${baseURL}/storage/images`,
  status: "status",
  refreshToken: "refresh-token",
  extraDemand: "ExtraDemand",
};
